/** biome-ignore-all lint/style/useNumericSeparators: better auth schema */
import {
  integer,
  json,
  numeric,
  pgEnum,
  pgTable,
  timestamp,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";

export const orderStatus = pgEnum("order_status", ["refunded", "delivered"]);

export const orders = pgTable("orders", {
  id: uuid("id").primaryKey().defaultRandom(),

  // Nome do cliente
  customer: varchar("customer", { length: 255 }).notNull(),

  // ID do pedido - # + 6 ~ 10 caracteres
  orderId: varchar("order_id", { length: 12 }).notNull().unique(),

  // Status no momento de cadastrar o produto. "refunded", "delivered"
  status: orderStatus(),

  // Título do banner do produto
  bannerTitle: varchar("banner_title", { length: 255 }),

  // Nome do produto
  productName: varchar("product_name", { length: 255 }).notNull(),

  // Categoria do produto (Genshin, Star Rail, etc.)
  category: varchar("category", { length: 255 }),

  // Plano de venda do anúncio na ggmax (Diamante, Gold, etc.)
  plan: varchar("plan", { length: 255 }).notNull(),
  quantity: integer("quantity").notNull(),
  unitPrice: numeric("unit_price", { precision: 10, scale: 2 })
    .notNull()
    .$type<number>(),

  // Subtotal do pedido
  subtotal: numeric("subtotal", { precision: 10, scale: 2 })
    .notNull()
    .$type<number>(),

  // Valor total do pedido descontando a comissão da GGMAX
  total: numeric("total", { precision: 10, scale: 2 })
    .notNull()
    .$type<number>(),

  // ID externo do pedido (e-mail do produto enviado)
  externalId: varchar("external_id", { length: 255 }),

  // userId: text("user_id").references(() => users.id),

  // Data de criação do pedido
  createdAt: timestamp("created_at").notNull(),
});

export type Order = typeof orders.$inferSelect;

export const inventoryBatches = pgTable("inventory_batches", {
  id: uuid("id").primaryKey().defaultRandom(),
  exchangeRate: numeric("exchange_rate", { precision: 10, scale: 4 })
    .notNull()
    .$type<number>(),
  price: numeric("price", { precision: 10, scale: 2 })
    .notNull()
    .$type<number>(),
  content: json("content").notNull().$type<string[]>(),
  messageId: varchar("message_id", { length: 255 }).notNull().unique(),
});

export type InventoryBatch = typeof inventoryBatches.$inferSelect;
export type NewInventoryBatch = typeof inventoryBatches.$inferInsert;

// // BetterAuth tables (generated by CLI)
// export const users = pgTable("user", {
//   id: text("id").primaryKey(),
//   name: text("name").notNull(),
//   email: text("email").notNull().unique(),
//   emailVerified: boolean("email_verified").default(false).notNull(),
//   image: text("image"),
//   createdAt: timestamp("created_at").defaultNow().notNull(),
//   updatedAt: timestamp("updated_at")
//     .defaultNow()
//     .$onUpdate(() => new Date())
//     .notNull(),
// });

// export const sessions = pgTable("session", {
//   id: text("id").primaryKey(),
//   expiresAt: timestamp("expires_at").notNull(),
//   token: text("token").notNull().unique(),
//   createdAt: timestamp("created_at").defaultNow().notNull(),
//   updatedAt: timestamp("updated_at")
//     .$onUpdate(() => new Date())
//     .notNull(),
//   ipAddress: text("ip_address"),
//   userAgent: text("user_agent"),
//   userId: text("user_id")
//     .notNull()
//     .references(() => users.id, { onDelete: "cascade" }),
// });

// export const accounts = pgTable("account", {
//   id: text("id").primaryKey(),
//   accountId: text("account_id").notNull(),
//   providerId: text("provider_id").notNull(),
//   userId: text("user_id")
//     .notNull()
//     .references(() => users.id, { onDelete: "cascade" }),
//   accessToken: text("access_token"),
//   refreshToken: text("refresh_token"),
//   idToken: text("id_token"),
//   accessTokenExpiresAt: timestamp("access_token_expires_at"),
//   refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
//   scope: text("scope"),
//   password: text("password"),
//   createdAt: timestamp("created_at").defaultNow().notNull(),
//   updatedAt: timestamp("updated_at")
//     .$onUpdate(() => new Date())
//     .notNull(),
// });

// export const verifications = pgTable("verification", {
//   id: text("id").primaryKey(),
//   identifier: text("identifier").notNull(),
//   value: text("value").notNull(),
//   expiresAt: timestamp("expires_at").notNull(),
//   createdAt: timestamp("created_at").defaultNow().notNull(),
//   updatedAt: timestamp("updated_at")
//     .$onUpdate(() => new Date())
//     .notNull(),
// });

// export const apikeys = pgTable("apikey", {
//   id: text("id").primaryKey(),
//   name: text("name"),
//   start: text("start"),
//   prefix: text("prefix"),
//   key: text("key").notNull(),
//   userId: text("user_id")
//     .notNull()
//     .references(() => users.id, { onDelete: "cascade" }),
//   refillInterval: integer("refill_interval"),
//   refillAmount: integer("refill_amount"),
//   lastRefillAt: timestamp("last_refill_at"),
//   enabled: boolean("enabled").default(true),
//   rateLimitEnabled: boolean("rate_limit_enabled").default(true),
//   rateLimitTimeWindow: integer("rate_limit_time_window").default(86400000),
//   rateLimitMax: integer("rate_limit_max").default(10),
//   requestCount: integer("request_count").default(0),
//   remaining: integer("remaining"),
//   lastRequest: timestamp("last_request"),
//   expiresAt: timestamp("expires_at"),
//   createdAt: timestamp("created_at").notNull(),
//   updatedAt: timestamp("updated_at").notNull(),
//   permissions: text("permissions"),
//   metadata: text("metadata"),
// });

// export type User = typeof users.$inferSelect;
// export type Session = typeof sessions.$inferSelect;
// export type Account = typeof accounts.$inferSelect;
// export type Verification = typeof verifications.$inferSelect;
// export type Apikey = typeof apikeys.$inferSelect;
